nlp = BROWNDEN()
@test !has_bounds(nlp)
@test !bound_constrained(nlp)
@test unconstrained(nlp)
@test !linearly_constrained(nlp)
@test !equality_constrained(nlp)
@test !inequality_constrained(nlp)

nlp = HS5()
@test has_bounds(nlp)
@test bound_constrained(nlp)
@test !unconstrained(nlp)
@test !linearly_constrained(nlp)
@test !equality_constrained(nlp)
@test !inequality_constrained(nlp)

nlp = HS6()
@test !has_bounds(nlp)
@test !bound_constrained(nlp)
@test !unconstrained(nlp)
@test !linearly_constrained(nlp)
@test equality_constrained(nlp)
@test !inequality_constrained(nlp)

nlp = HS10()
@test !has_bounds(nlp)
@test !bound_constrained(nlp)
@test !unconstrained(nlp)
@test !linearly_constrained(nlp)
@test !equality_constrained(nlp)
@test inequality_constrained(nlp)

nlp = HS14()
@test !has_bounds(nlp)
@test !bound_constrained(nlp)
@test !unconstrained(nlp)
@test !linearly_constrained(nlp)
@test !equality_constrained(nlp)
@test !inequality_constrained(nlp)

#= Implement after QuadraticModels is merged inside NLPModels
nlp = ???
@test !has_bounds(nlp)
@test !bound_constrained(nlp)
@test !unconstrained(nlp)
@test linearly_constrained(nlp)
@test equality_constrained(nlp)
@test !inequality_constrained(nlp)

nlp = ???
@test has_bounds(nlp)
@test !bound_constrained(nlp)
@test !unconstrained(nlp)
@test linearly_constrained(nlp)
@test equality_constrained(nlp)
@test !inequality_constrained(nlp)
=#
